
about :

  name : listing
  description : "Module for listing"
  version : 0.0.1

path :

  in : 'in'
  out : 'out'
  export : 'proto'

step :

  export.proto :
      inherit : export
      tar : 0
      export : path::export

build :

  export :
      criterion :
          default : 1
          export : 1
      steps :
          - export.proto