
submodule :

  Tools : git+https:///github.com/Wandalen/wTools.git/!master
  PathBasic : git+https:///github.com/Wandalen/wPathBasic.git/!master

path :

  build : build
  proto : proto

reflector :

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exported.files*=1
    dst :
      prefixPath : path::build
    src :
      maskAll :
          excludeAny :
            - !!js/regexp '/\.test/'
    criterion :
      debug : 1

  reflect.proto :
    src : path::proto
    dst : path::build
    criterion :
      debug : 1

step :

  delete.build :
    inherit : files.delete
    filePath : '{path::build}/**'
    criterion :
      debug : 1

build :

  build :
    steps :
      - step::delete.build
      - step::reflect.submodules
      - step::reflect.proto
    criterion :
      default : 1
