name : math_adapter

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/rust/math_adapter/Cargo.toml'
      module_name : 'math_adapter'
      commit_message : ${{ github.event.head_commit.message }}
